export type PoiCategory =
  | "ATTRACTION"
  | "RESTAURANT"
  | "HOTEL"
  | "SHOPPING"
  | "SERVICE"
  | "SCHOOL"
  | "TRANSPORT"
  | "BASE"
  | "HOSPITAL"
  | "EVENT";

  type PlaceCategory = Exclude<PoiCategory, "EVENT">;


export type DayCode =
  | "sun"
  | "mon"
  | "tue"
  | "wed"
  | "thu"
  | "fri"
  | "sat";

export type HoursEntry =
  | { type: "24_7" }
  | {
      type: "custom";
      days: DayCode[];
      open: string;
      close: string;
    };


export type Poi = {
  id: string;
  name: string;
  village: string;
  villageId: string;
  lat: number;
  lng: number;
  category: PlaceCategory;
  type: PlaceCategory;
  source: string;
  hoursText: string;
  description: string;
  verified: boolean;
  hours?: HoursEntry[];
};

export type EventItem = {
  id: string;
  title: string;
  villageId: string;
  lat: number;
  lng: number;
  status: "VERIFIED" | "PENDING";
  source: string;
  when: string;
  description: string;
};

export type LiveHotspot = {
  id: string;
  label: string;
  lat: number;
  lng: number;
  count: number;
};

export const CATEGORY_META: Record<
  PoiCategory,
  { label: string; color: string; bg: string; icon: string }
> = {
  ATTRACTION: {
    label: "Attraction",
    color: "#38bdf8",
    bg: "rgba(56, 189, 248, 0.14)",
    icon: "📸",
  },
  RESTAURANT: {
    label: "Restaurant",
    color: "#f97316",
    bg: "rgba(249, 115, 22, 0.14)",
    icon: "🍽️",
  },
  HOTEL: {
    label: "Hotel",
    color: "#a78bfa",
    bg: "rgba(167, 139, 250, 0.14)",
    icon: "🏨",
  },
  SHOPPING: {
    label: "Shopping",
    color: "#facc15",
    bg: "rgba(250, 204, 21, 0.14)",
    icon: "🛍️",
  },
  SERVICE: {
    label: "Service",
    color: "#22c55e",
    bg: "rgba(34, 197, 94, 0.14)",
    icon: "🛠️",
  },
  SCHOOL: {
    label: "School",
    color: "#60a5fa",
    bg: "rgba(96, 165, 250, 0.14)",
    icon: "🎓",
  },
  TRANSPORT: {
    label: "Transport",
    color: "#fb7185",
    bg: "rgba(251, 113, 133, 0.14)",
    icon: "🚗",
  },
  BASE: {
    label: "Base",
    color: "#94a3b8",
    bg: "rgba(148, 163, 184, 0.14)",
    icon: "🪖",
  },
  HOSPITAL: {
    label: "Hospital",
    color: "#ef4444",
    bg: "rgba(239, 68, 68, 0.14)",
    icon: "🏥",
  },
  EVENT: {
    label: "Event",
    color: "#14b8a6",
    bg: "rgba(20, 184, 166, 0.14)",
    icon: "🎉",
  },
};

const DAY_CODES: DayCode[] = ["sun", "mon", "tue", "wed", "thu", "fri", "sat"];

function toMinutes(hhmm: string): number {
  const [h, m] = hhmm.split(":").map(Number);
  return h * 60 + m;
}

export function isPoiOpenNow(poi: { hours?: HoursEntry[] }, now = new Date()): boolean | null {
  if (!poi.hours || poi.hours.length === 0) return null;

  const day = DAY_CODES[now.getDay()];
  const currentMinutes = now.getHours() * 60 + now.getMinutes();

  for (const entry of poi.hours) {
    if (entry.type === "24_7") return true;
    if (!entry.days.includes(day)) continue;

    const openMinutes = toMinutes(entry.open);
    const closeMinutes = toMinutes(entry.close);

    if (closeMinutes > openMinutes) {
      if (currentMinutes >= openMinutes && currentMinutes < closeMinutes) return true;
    } else {
      if (currentMinutes >= openMinutes || currentMinutes < closeMinutes) return true;
    }
  }

  return false;
}

export function getPoiOpenText(poi: { hours?: HoursEntry[] }, now = new Date()): string {
  const open = isPoiOpenNow(poi, now);
  if (open === null) return "Hours unavailable";
  return open ? "Open now" : "Closed now";
}

export function getCategoryColor(category: PoiCategory) {
  return CATEGORY_META[category]?.color ?? "#94a3b8";
}

export function getCategoryBg(category: PoiCategory) {
  return CATEGORY_META[category]?.bg ?? "rgba(148, 163, 184, 0.14)";
}

export function getCategoryIcon(category: PoiCategory) {
  return CATEGORY_META[category]?.icon ?? "📍";
}

export function getCategoryLabel(category: PoiCategory) {
  return CATEGORY_META[category]?.label ?? category;
}

export const POIS: Poi[] = [
  {
    id: "micronesia-mall",
    name: "Micronesia Mall",
    village: "Dededo",
    villageId: "dededo",
    lat: 13.5175,
    lng: 144.839,
    category: "SHOPPING",
    type: "SHOPPING",
    source: "Curated Seed Data",
    hoursText: "Open daily",
    description: "Large shopping mall with retail stores, restaurants, and a movie theater.",
    verified: true,
    hours: [{ type: "custom", days: ["mon", "tue", "wed", "thu", "fri", "sat", "sun"], open: "10:00", close: "21:00" }],
  },
  {
    id: "mobil-dededo",
    name: "Mobil Gas Station Dededo",
    village: "Dededo",
    villageId: "dededo",
    lat: 13.5155,
    lng: 144.8382,
    category: "SERVICE",
    type: "SERVICE",
    source: "Curated Seed Data",
    hoursText: "24/7",
    description: "Gas station and convenience stop in Dededo for fuel, snacks, and drinks.",
    verified: false,
    hours: [{ type: "24_7" }],
  },
  {
    id: "astumbo-park",
    name: "Astumbo Park",
    village: "Dededo",
    villageId: "dededo",
    lat: 13.53,
    lng: 144.85,
    category: "ATTRACTION",
    type: "ATTRACTION",
    source: "Curated Seed Data",
    hoursText: "Open daily",
    description: "Community park area with open space and recreational facilities.",
    verified: false,
  },
  {
    id: "dededo-flea-market",
    name: "Dededo Flea Market",
    village: "Dededo",
    villageId: "dededo",
    lat: 13.517,
    lng: 144.84,
    category: "SHOPPING",
    type: "SHOPPING",
    source: "Curated Seed Data",
    hoursText: "Weekend mornings",
    description: "Popular flea market with local vendors, food, and bargain shopping.",
    verified: false,
  },
  {
    id: "payless-dededo",
    name: "Payless Supermarket Dededo",
    village: "Dededo",
    villageId: "dededo",
    lat: 13.524,
    lng: 144.846,
    category: "SHOPPING",
    type: "SHOPPING",
    source: "Curated Seed Data",
    hoursText: "Daily • 6am–11pm",
    description: "Large supermarket in Dededo.",
    verified: true,
    hours: [{ type: "custom", days: ["mon","tue","wed","thu","fri","sat","sun"], open: "06:00", close: "23:00" }],
  },
  {
    id: "dededo-sports-complex",
    name: "Dededo Sports Complex",
    village: "Dededo",
    villageId: "dededo",
    lat: 13.529,
    lng: 144.848,
    category: "ATTRACTION",
    type: "ATTRACTION",
    source: "Curated Seed Data",
    hoursText: "Open daily",
    description: "Public sports and recreation complex.",
    verified: false,
  },

  {
    id: "tumon-bay",
    name: "Tumon Bay Beach",
    village: "Tamuning",
    villageId: "tamuning",
    lat: 13.505,
    lng: 144.802,
    category: "ATTRACTION",
    type: "ATTRACTION",
    source: "Curated Seed Data",
    hoursText: "Open daily",
    description: "Popular beach area with clear water, hotels, shopping, and nightlife nearby.",
    verified: true,
  },
  {
    id: "two-lovers-point",
    name: "Two Lovers Point",
    village: "Tamuning",
    villageId: "tamuning",
    lat: 13.517,
    lng: 144.804,
    category: "ATTRACTION",
    type: "ATTRACTION",
    source: "Curated Seed Data",
    hoursText: "Open daily",
    description: "Famous scenic cliffside viewpoint overlooking the ocean and Tumon Bay.",
    verified: true,
    hours: [{ type: "custom", days: ["mon","tue","wed","thu","fri","sat","sun"], open: "07:00", close: "19:00" }],
  },
  {
    id: "dfs-galleria",
    name: "DFS Galleria",
    village: "Tamuning",
    villageId: "tamuning",
    lat: 13.5065,
    lng: 144.8025,
    category: "SHOPPING",
    type: "SHOPPING",
    source: "Curated Seed Data",
    hoursText: "Open daily",
    description: "Duty-free luxury shopping center in the heart of Tumon tourist district.",
    verified: true,
    hours: [{ type: "custom", days: ["mon","tue","wed","thu","fri","sat","sun"], open: "10:00", close: "22:00" }],
  },
  {
    id: "dusit-thani-guam",
    name: "Dusit Thani Guam Resort",
    village: "Tamuning",
    villageId: "tamuning",
    lat: 13.5056,
    lng: 144.8023,
    category: "HOTEL",
    type: "HOTEL",
    source: "Curated Seed Data",
    hoursText: "24/7",
    description: "High-rise beachfront resort hotel in Tumon with restaurants and ocean views.",
    verified: true,
    hours: [{ type: "24_7" }],
  },
  {
    id: "proa-tumon",
    name: "Proa Restaurant",
    village: "Tamuning",
    villageId: "tamuning",
    lat: 13.5065,
    lng: 144.801,
    category: "RESTAURANT",
    type: "RESTAURANT",
    source: "Curated Seed Data",
    hoursText: "Daily • 11am–9pm",
    description: "Popular local favorite for Chamorro fusion dishes.",
    verified: true,
    hours: [{ type: "custom", days: ["mon","tue","wed","thu","fri","sat","sun"], open: "11:00", close: "21:00" }],
  },
  {
    id: "guam-premier-outlets",
    name: "Guam Premier Outlets",
    village: "Tamuning",
    villageId: "tamuning",
    lat: 13.489,
    lng: 144.782,
    category: "SHOPPING",
    type: "SHOPPING",
    source: "Curated Seed Data",
    hoursText: "Daily • 10am–9pm",
    description: "Outlet mall with shopping, dining, and entertainment.",
    verified: true,
    hours: [{ type: "custom", days: ["mon","tue","wed","thu","fri","sat","sun"], open: "10:00", close: "21:00" }],
  },
  {
    id: "tumon-sands-plaza",
    name: "Tumon Sands Plaza",
    village: "Tamuning",
    villageId: "tamuning",
    lat: 13.5057,
    lng: 144.8015,
    category: "SHOPPING",
    type: "SHOPPING",
    source: "Curated Seed Data",
    hoursText: "Daily • 10am–9pm",
    description: "Luxury shopping center in Tumon.",
    verified: true,
  },
  {
    id: "hotel-nikko-guam",
    name: "Hotel Nikko Guam",
    village: "Tamuning",
    villageId: "tamuning",
    lat: 13.5184,
    lng: 144.806,
    category: "HOTEL",
    type: "HOTEL",
    source: "Curated Seed Data",
    hoursText: "24/7",
    description: "Beachfront hotel in upper Tumon.",
    verified: true,
    hours: [{ type: "24_7" }],
  },

  {
    id: "chamorro-village",
    name: "Chamorro Village",
    village: "Hagatna",
    villageId: "hagatna",
    lat: 13.475,
    lng: 144.75,
    category: "ATTRACTION",
    type: "ATTRACTION",
    source: "Curated Seed Data",
    hoursText: "Wed • 6pm–9pm",
    description: "Cultural marketplace with food, crafts, events, and local vendors.",
    verified: true,
    hours: [{ type: "custom", days: ["wed"], open: "18:00", close: "21:00" }],
  },
  {
    id: "latte-stone-park",
    name: "Latte Stone Park",
    village: "Hagatna",
    villageId: "hagatna",
    lat: 13.4758,
    lng: 144.751,
    category: "ATTRACTION",
    type: "ATTRACTION",
    source: "Curated Seed Data",
    hoursText: "Open daily",
    description: "Historic site featuring ancient Chamorro latte stones and cultural significance.",
    verified: true,
  },
  {
    id: "plaza-de-espana",
    name: "Plaza de España",
    village: "Hagatna",
    villageId: "hagatna",
    lat: 13.4745,
    lng: 144.7495,
    category: "ATTRACTION",
    type: "ATTRACTION",
    source: "Curated Seed Data",
    hoursText: "Open daily",
    description: "Historic Spanish-era plaza and one of the major landmark sites in Hagåtña.",
    verified: true,
  },
  {
    id: "hagatna-bus-terminal",
    name: "Hagåtña Bus Terminal",
    village: "Hagatna",
    villageId: "hagatna",
    lat: 13.4748,
    lng: 144.7505,
    category: "TRANSPORT",
    type: "TRANSPORT",
    source: "Curated Seed Data",
    hoursText: "Daily",
    description: "Main public transportation hub.",
    verified: false,
  },
  {
    id: "guam-museum",
    name: "Guam Museum",
    village: "Hagatna",
    villageId: "hagatna",
    lat: 13.4741,
    lng: 144.7516,
    category: "ATTRACTION",
    type: "ATTRACTION",
    source: "Curated Seed Data",
    hoursText: "Tue–Sun • 10am–5pm",
    description: "Museum featuring Guam history and culture.",
    verified: true,
  },

  {
    id: "university-of-guam",
    name: "University of Guam",
    village: "Mangilao",
    villageId: "mangilao",
    lat: 13.4443,
    lng: 144.8,
    category: "SCHOOL",
    type: "SCHOOL",
    source: "Curated Seed Data",
    hoursText: "Mon–Fri • 8am–5pm",
    description: "Main university campus on Guam.",
    verified: true,
    hours: [{ type: "custom", days: ["mon","tue","wed","thu","fri"], open: "08:00", close: "17:00" }],
  },
  {
    id: "guam-community-college",
    name: "Guam Community College",
    village: "Mangilao",
    villageId: "mangilao",
    lat: 13.447,
    lng: 144.79,
    category: "SCHOOL",
    type: "SCHOOL",
    source: "Curated Seed Data",
    hoursText: "Mon–Fri • 8am–5pm",
    description: "Technical and vocational college serving students across Guam.",
    verified: true,
    hours: [{ type: "custom", days: ["mon","tue","wed","thu","fri"], open: "08:00", close: "17:00" }],
  },
  {
    id: "uog-library",
    name: "UOG Library",
    village: "Mangilao",
    villageId: "mangilao",
    lat: 13.444,
    lng: 144.801,
    category: "SCHOOL",
    type: "SCHOOL",
    source: "Curated Seed Data",
    hoursText: "Mon–Fri • 8am–5pm",
    description: "University library and study space.",
    verified: true,
  },
  {
    id: "mangilao-golf-club",
    name: "Onward Mangilao Golf Club",
    village: "Mangilao",
    villageId: "mangilao",
    lat: 13.442,
    lng: 144.821,
    category: "ATTRACTION",
    type: "ATTRACTION",
    source: "Curated Seed Data",
    hoursText: "Daily",
    description: "Scenic golf course overlooking the ocean.",
    verified: true,
  },
  {
    id: "payless-mangilao",
    name: "Payless Supermarket Mangilao",
    village: "Mangilao",
    villageId: "mangilao",
    lat: 13.4478,
    lng: 144.799,
    category: "SHOPPING",
    type: "SHOPPING",
    source: "Curated Seed Data",
    hoursText: "Daily • 6am–11pm",
    description: "Major grocery and convenience store.",
    verified: true,
  },

  {
    id: "antonio-won-pat-airport",
    name: "Antonio B. Won Pat International Airport",
    village: "Barrigada",
    villageId: "barrigada",
    lat: 13.483,
    lng: 144.796,
    category: "TRANSPORT",
    type: "TRANSPORT",
    source: "Curated Seed Data",
    hoursText: "24/7",
    description: "Main airport on Guam handling domestic and international flights.",
    verified: true,
    hours: [{ type: "24_7" }],
  },
  {
    id: "happy-mart-barrigada",
    name: "Happy Mart Barrigada",
    village: "Barrigada",
    villageId: "barrigada",
    lat: 13.4835,
    lng: 144.804,
    category: "SHOPPING",
    type: "SHOPPING",
    source: "Curated Seed Data",
    hoursText: "Daily • 7am–10pm",
    description: "Local grocery store in Barrigada.",
    verified: true,
  },
  {
    id: "guam-police-hq",
    name: "Guam Police Department HQ",
    village: "Barrigada",
    villageId: "barrigada",
    lat: 13.49,
    lng: 144.81,
    category: "SERVICE",
    type: "SERVICE",
    source: "Curated Seed Data",
    hoursText: "24/7",
    description: "Main police headquarters.",
    verified: true,
    hours: [{ type: "24_7" }],
  },
  {
    id: "barrigada-mayors-office",
    name: "Barrigada Mayor's Office",
    village: "Barrigada",
    villageId: "barrigada",
    lat: 13.47,
    lng: 144.801,
    category: "SERVICE",
    type: "SERVICE",
    source: "Curated Seed Data",
    hoursText: "Mon–Fri • 8am–5pm",
    description: "Municipal government office.",
    verified: false,
  },
  {
    id: "st-francis-school",
    name: "St. Francis Catholic School",
    village: "Barrigada",
    villageId: "barrigada",
    lat: 13.476,
    lng: 144.803,
    category: "SCHOOL",
    type: "SCHOOL",
    source: "Curated Seed Data",
    hoursText: "Mon–Fri",
    description: "Private school in Barrigada.",
    verified: false,
  },

  {
    id: "andersen-air-force-base",
    name: "Andersen Air Force Base",
    village: "Yigo",
    villageId: "yigo",
    lat: 13.583,
    lng: 144.93,
    category: "BASE",
    type: "BASE",
    source: "Curated Seed Data",
    hoursText: "Restricted access",
    description: "Major U.S. Air Force installation in northern Guam.",
    verified: false,
  },
  {
    id: "ritidian-point",
    name: "Ritidian Point",
    village: "Yigo",
    villageId: "yigo",
    lat: 13.654,
    lng: 144.867,
    category: "ATTRACTION",
    type: "ATTRACTION",
    source: "Curated Seed Data",
    hoursText: "Open daily",
    description: "Remote beach and wildlife refuge area known for nature and scenery.",
    verified: true,
  },
  {
    id: "ritidian-beach",
    name: "Ritidian Beach",
    village: "Yigo",
    villageId: "yigo",
    lat: 13.654,
    lng: 144.867,
    category: "ATTRACTION",
    type: "ATTRACTION",
    source: "Curated Seed Data",
    hoursText: "Daily • 7:30am–4pm",
    description: "Remote scenic beach and wildlife refuge destination.",
    verified: true,
    hours: [{ type: "custom", days: ["mon","tue","wed","thu","fri","sat","sun"], open: "07:30", close: "16:00" }],
  },
  {
    id: "payless-yigo",
    name: "Payless Supermarket Yigo",
    village: "Yigo",
    villageId: "yigo",
    lat: 13.536,
    lng: 144.89,
    category: "SHOPPING",
    type: "SHOPPING",
    source: "Curated Seed Data",
    hoursText: "Daily • 6am–11pm",
    description: "Popular grocery and convenience stop in northern Guam.",
    verified: true,
    hours: [{ type: "custom", days: ["mon","tue","wed","thu","fri","sat","sun"], open: "06:00", close: "23:00" }],
  },
  {
    id: "yigo-mayors-office",
    name: "Yigo Mayor's Office",
    village: "Yigo",
    villageId: "yigo",
    lat: 13.548,
    lng: 144.903,
    category: "SERVICE",
    type: "SERVICE",
    source: "Curated Seed Data",
    hoursText: "Mon–Fri • 8am–5pm",
    description: "Village municipal office.",
    verified: false,
  },

  {
    id: "pago-bay",
    name: "Pago Bay",
    village: "Yona",
    villageId: "yona",
    lat: 13.402,
    lng: 144.77,
    category: "ATTRACTION",
    type: "ATTRACTION",
    source: "Curated Seed Data",
    hoursText: "Open daily",
    description: "Scenic bay area known for ocean views and coastal recreation.",
    verified: false,
  },
  {
    id: "leo-palace",
    name: "LeoPalace Resort",
    village: "Yona",
    villageId: "yona",
    lat: 13.42,
    lng: 144.77,
    category: "HOTEL",
    type: "HOTEL",
    source: "Curated Seed Data",
    hoursText: "24/7",
    description: "Large resort complex with golf, lodging, and event facilities.",
    verified: true,
    hours: [{ type: "24_7" }],
  },
  {
    id: "yona-store",
    name: "Yona Store",
    village: "Yona",
    villageId: "yona",
    lat: 13.409,
    lng: 144.777,
    category: "SHOPPING",
    type: "SHOPPING",
    source: "Curated Seed Data",
    hoursText: "Daily",
    description: "Small local convenience market.",
    verified: false,
  },
  {
    id: "windward-hills",
    name: "Windward Hills Golf Club",
    village: "Yona",
    villageId: "yona",
    lat: 13.416,
    lng: 144.785,
    category: "ATTRACTION",
    type: "ATTRACTION",
    source: "Curated Seed Data",
    hoursText: "Daily",
    description: "Golf and recreation area in Yona.",
    verified: false,
  },

  {
    id: "talofofo-falls",
    name: "Talofofo Falls",
    village: "Talofofo",
    villageId: "talofofo",
    lat: 13.355,
    lng: 144.75,
    category: "ATTRACTION",
    type: "ATTRACTION",
    source: "Curated Seed Data",
    hoursText: "Daily • 9am–5pm",
    description: "Well-known waterfall attraction and sightseeing destination.",
    verified: true,
    hours: [{ type: "custom", days: ["mon","tue","wed","thu","fri","sat","sun"], open: "09:00", close: "17:00" }],
  },
  {
    id: "jeffs-pirates-cove",
    name: "Jeff’s Pirates Cove",
    village: "Talofofo",
    villageId: "talofofo",
    lat: 13.24,
    lng: 144.75,
    category: "RESTAURANT",
    type: "RESTAURANT",
    source: "Curated Seed Data",
    hoursText: "Daily • 11am–8pm",
    description: "Popular seaside restaurant and Guam landmark.",
    verified: true,
    hours: [{ type: "custom", days: ["mon","tue","wed","thu","fri","sat","sun"], open: "11:00", close: "20:00" }],
  },
  {
    id: "talofofo-bay-lookout",
    name: "Talofofo Bay Lookout",
    village: "Talofofo",
    villageId: "talofofo",
    lat: 13.343,
    lng: 144.764,
    category: "ATTRACTION",
    type: "ATTRACTION",
    source: "Curated Seed Data",
    hoursText: "Open daily",
    description: "Scenic overlook near Talofofo Bay.",
    verified: false,
  },
  {
    id: "talofofo-mayors-office",
    name: "Talofofo Mayor's Office",
    village: "Talofofo",
    villageId: "talofofo",
    lat: 13.354,
    lng: 144.757,
    category: "SERVICE",
    type: "SERVICE",
    source: "Curated Seed Data",
    hoursText: "Mon–Fri • 8am–5pm",
    description: "Village municipal office.",
    verified: false,
  },

  {
    id: "inalahan-natural-pool",
    name: "Inalåhan Natural Pool",
    village: "Inalahan",
    villageId: "inalahan",
    lat: 13.273,
    lng: 144.748,
    category: "ATTRACTION",
    type: "ATTRACTION",
    source: "Curated Seed Data",
    hoursText: "Open daily",
    description: "Natural seaside pool protected by rocks and popular for swimming.",
    verified: true,
  },
  {
    id: "gef-pago",
    name: "Gef Pa'go Cultural Village",
    village: "Inalahan",
    villageId: "inalahan",
    lat: 13.2735,
    lng: 144.7495,
    category: "ATTRACTION",
    type: "ATTRACTION",
    source: "Curated Seed Data",
    hoursText: "Open daily",
    description: "Cultural village preserving traditional Chamorro life.",
    verified: true,
  },
  {
    id: "inalahan-mayors-office",
    name: "Inalåhan Mayor's Office",
    village: "Inalahan",
    villageId: "inalahan",
    lat: 13.274,
    lng: 144.747,
    category: "SERVICE",
    type: "SERVICE",
    source: "Curated Seed Data",
    hoursText: "Mon–Fri • 8am–5pm",
    description: "Village municipal office.",
    verified: false,
  },

  {
    id: "cocos-island-ferry",
    name: "Cocos Island Ferry",
    village: "Malesso",
    villageId: "malesso",
    lat: 13.255,
    lng: 144.67,
    category: "TRANSPORT",
    type: "TRANSPORT",
    source: "Curated Seed Data",
    hoursText: "Daily • 8am–5pm",
    description: "Boat access point for visitors heading to Cocos Island.",
    verified: true,
    hours: [{ type: "custom", days: ["mon","tue","wed","thu","fri","sat","sun"], open: "08:00", close: "17:00" }],
  },
  {
    id: "fort-our-lady",
    name: "Fort Nuestra Señora de la Soledad Viewpoint",
    village: "Malesso",
    villageId: "malesso",
    lat: 13.249,
    lng: 144.669,
    category: "ATTRACTION",
    type: "ATTRACTION",
    source: "Curated Seed Data",
    hoursText: "Open daily",
    description: "Southern scenic viewpoint near the coast.",
    verified: false,
  },
  {
    id: "malesso-pier",
    name: "Malesso Pier",
    village: "Malesso",
    villageId: "malesso",
    lat: 13.252,
    lng: 144.671,
    category: "TRANSPORT",
    type: "TRANSPORT",
    source: "Curated Seed Data",
    hoursText: "Open daily",
    description: "Pier and water access point in Malesso.",
    verified: false,
  },

  {
    id: "umatac-bay",
    name: "Umatac Bay",
    village: "Humåtak",
    villageId: "humatak",
    lat: 13.305,
    lng: 144.66,
    category: "ATTRACTION",
    type: "ATTRACTION",
    source: "Curated Seed Data",
    hoursText: "Open daily",
    description: "Historic southern bay with scenic coastal views and local significance.",
    verified: true,
  },
  {
    id: "fort-soledad",
    name: "Fort Soledad",
    village: "Humåtak",
    villageId: "humatak",
    lat: 13.31,
    lng: 144.66,
    category: "ATTRACTION",
    type: "ATTRACTION",
    source: "Curated Seed Data",
    hoursText: "Open daily",
    description: "Historic Spanish fort overlooking the southern coastline.",
    verified: true,
  },
  {
    id: "humatak-mayors-office",
    name: "Humåtak Mayor's Office",
    village: "Humåtak",
    villageId: "humatak",
    lat: 13.304,
    lng: 144.659,
    category: "SERVICE",
    type: "SERVICE",
    source: "Curated Seed Data",
    hoursText: "Mon–Fri • 8am–5pm",
    description: "Village municipal office.",
    verified: false,
  },

  {
    id: "fish-eye-marine-park",
    name: "Fish Eye Marine Park",
    village: "Piti",
    villageId: "piti",
    lat: 13.458,
    lng: 144.693,
    category: "ATTRACTION",
    type: "ATTRACTION",
    source: "Curated Seed Data",
    hoursText: "Daily • 9am–6pm",
    description: "Marine park with underwater observatory and ocean activities.",
    verified: true,
    hours: [{ type: "custom", days: ["mon","tue","wed","thu","fri","sat","sun"], open: "09:00", close: "18:00" }],
  },
  {
    id: "piti-bombs",
    name: "Piti Bomb Holes",
    village: "Piti",
    villageId: "piti",
    lat: 13.469,
    lng: 144.692,
    category: "ATTRACTION",
    type: "ATTRACTION",
    source: "Curated Seed Data",
    hoursText: "Open daily",
    description: "Well-known snorkeling and reef area.",
    verified: false,
  },
  {
    id: "piti-power-plant",
    name: "Piti Power Plant Area",
    village: "Piti",
    villageId: "piti",
    lat: 13.459,
    lng: 144.689,
    category: "SERVICE",
    type: "SERVICE",
    source: "Curated Seed Data",
    hoursText: "Restricted",
    description: "Major infrastructure area in Piti.",
    verified: false,
  },

  {
    id: "agat-beach-park",
    name: "Agat Beach Park",
    village: "Agat",
    villageId: "agat",
    lat: 13.38,
    lng: 144.66,
    category: "ATTRACTION",
    type: "ATTRACTION",
    source: "Curated Seed Data",
    hoursText: "Open daily",
    description: "Public beach park with picnic areas and ocean access.",
    verified: false,
  },
  {
    id: "agat-marina",
    name: "Agat Marina",
    village: "Agat",
    villageId: "agat",
    lat: 13.386,
    lng: 144.65,
    category: "TRANSPORT",
    type: "TRANSPORT",
    source: "Curated Seed Data",
    hoursText: "Open daily",
    description: "Small marina area with ocean views and boat access.",
    verified: false,
  },
  {
    id: "agat-mayors-office",
    name: "Agat Mayor's Office",
    village: "Agat",
    villageId: "agat",
    lat: 13.388,
    lng: 144.658,
    category: "SERVICE",
    type: "SERVICE",
    source: "Curated Seed Data",
    hoursText: "Mon–Fri • 8am–5pm",
    description: "Village municipal office.",
    verified: false,
  },

  {
    id: "war-in-the-pacific-park",
    name: "War in the Pacific National Historical Park",
    village: "Asan-Maina",
    villageId: "asan-maina",
    lat: 13.46,
    lng: 144.72,
    category: "ATTRACTION",
    type: "ATTRACTION",
    source: "Curated Seed Data",
    hoursText: "Open daily",
    description: "WWII memorial and historical park with preserved sites and exhibits.",
    verified: true,
  },
  {
    id: "asan-beach",
    name: "Asan Beach Unit",
    village: "Asan-Maina",
    villageId: "asan-maina",
    lat: 13.464,
    lng: 144.724,
    category: "ATTRACTION",
    type: "ATTRACTION",
    source: "Curated Seed Data",
    hoursText: "Open daily",
    description: "Historic beach unit of the park.",
    verified: false,
  },

  {
    id: "sinajana-playground",
    name: "Sinajana Playground",
    village: "Sinajana",
    villageId: "sinajana",
    lat: 13.465,
    lng: 144.76,
    category: "ATTRACTION",
    type: "ATTRACTION",
    source: "Curated Seed Data",
    hoursText: "Open daily",
    description: "Community playground and open recreational area.",
    verified: false,
  },
  {
    id: "sinajana-mayors-office",
    name: "Sinajana Mayor's Office",
    village: "Sinajana",
    villageId: "sinajana",
    lat: 13.464,
    lng: 144.759,
    category: "SERVICE",
    type: "SERVICE",
    source: "Curated Seed Data",
    hoursText: "Mon–Fri • 8am–5pm",
    description: "Village municipal office.",
    verified: false,
  },

  {
    id: "guam-memorial-hospital",
    name: "Guam Memorial Hospital",
    village: "Mongmong-Toto-Maite",
    villageId: "mongmong-toto-maite",
    lat: 13.4705,
    lng: 144.7605,
    category: "HOSPITAL",
    type: "HOSPITAL",
    source: "Curated Seed Data",
    hoursText: "24/7",
    description: "Main public hospital serving residents across Guam.",
    verified: true,
    hours: [{ type: "24_7" }],
  },
  {
    id: "payless-maite",
    name: "Payless Supermarket Maite",
    village: "Mongmong-Toto-Maite",
    villageId: "mongmong-toto-maite",
    lat: 13.47,
    lng: 144.77,
    category: "SHOPPING",
    type: "SHOPPING",
    source: "Curated Seed Data",
    hoursText: "Daily • 6am–11pm",
    description: "Popular grocery store in Maite.",
    verified: true,
  },
  {
    id: "maite-fire-station",
    name: "Maite Fire Station",
    village: "Mongmong-Toto-Maite",
    villageId: "mongmong-toto-maite",
    lat: 13.471,
    lng: 144.762,
    category: "SERVICE",
    type: "SERVICE",
    source: "Curated Seed Data",
    hoursText: "24/7",
    description: "Emergency service station.",
    verified: false,
    hours: [{ type: "24_7" }],
  },

  {
    id: "fort-apugan",
    name: "Fort Apugan",
    village: "Agana Heights",
    villageId: "agana-heights",
    lat: 13.47,
    lng: 144.745,
    category: "ATTRACTION",
    type: "ATTRACTION",
    source: "Curated Seed Data",
    hoursText: "Open daily",
    description: "Elevated viewpoint overlooking Hagåtña and nearby areas.",
    verified: false,
  },
  {
    id: "naval-hospital-guam",
    name: "US Naval Hospital Guam",
    village: "Agana Heights",
    villageId: "agana-heights",
    lat: 13.478,
    lng: 144.749,
    category: "HOSPITAL",
    type: "HOSPITAL",
    source: "Curated Seed Data",
    hoursText: "24/7",
    description: "Military hospital facility.",
    verified: true,
    hours: [{ type: "24_7" }],
  },
  {
    id: "agana-heights-mayors-office",
    name: "Agana Heights Mayor's Office",
    village: "Agana Heights",
    villageId: "agana-heights",
    lat: 13.472,
    lng: 144.746,
    category: "SERVICE",
    type: "SERVICE",
    source: "Curated Seed Data",
    hoursText: "Mon–Fri • 8am–5pm",
    description: "Village municipal office.",
    verified: false,
  },
];

export const PLACES = POIS.map((poi) => ({
  id: poi.id,
  name: poi.name,
  village: poi.village,
  villageId: poi.villageId,
  lat: poi.lat,
  lng: poi.lng,
  type: poi.category,
  category: poi.category,
  source: poi.verified ? "Admin Verified" : poi.source,
  hours: poi.hoursText,
  description: poi.description,
  verified: poi.verified,
  rawHours: poi.hours,
  tags: [poi.category.toLowerCase(), poi.village.toLowerCase()],
}));

export const EVENTS: EventItem[] = [
  {
    id: "chamorro-night-market-demo",
    title: "Chamorro Night Market (Demo)",
    villageId: "hagatna",
    lat: 13.4752,
    lng: 144.7502,
    status: "VERIFIED",
    source: "Admin Verified",
    when: "Wed • 6pm–9pm (example)",
    description: "Demo event entry for a weekly village market experience.",
  },
];

export const LIVE: LiveHotspot[] = [
  {
    id: "live-tumon",
    label: "Tumon activity",
    lat: 13.506,
    lng: 144.803,
    count: 22,
  },
  {
    id: "live-mall",
    label: "Micronesia Mall activity",
    lat: 13.5175,
    lng: 144.839,
    count: 15,
  },
  {
    id: "live-hagatna",
    label: "Hagåtña activity",
    lat: 13.475,
    lng: 144.75,
    count: 9,
  },
];